## 1. Write a Python Program to Add two Matrices ?

In [14]:
from numpy import*
M1=matrix("1 2 3 ; 4 5 6 ; 7 8 9")
print(" first Matrix is: ", M1)
M2=matrix("9 8 7 ; 6 5 4 ; 3 2 1")
print("second matrix is: ",M2)
M3=M1+M2
print("Addition of matrix is: ",M3)

 first Matrix is:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
second matrix is:  [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition of matrix is:  [[10 10 10]
 [10 10 10]
 [10 10 10]]


## 2. Write a Python Program to Multiply two Matrices ?

In [8]:
from numpy import*
M1=matrix("1 2 3 ; 4 5 6 ; 7 8 9")
print(" first Matrix is: ",M1)
M2=matrix("9 8 7 ; 6 5 4 ; 3 2 1")
print("second matrix is: ",M2)
M3=M1*M2
print("Multiplication of matrix is: ",M3)

 first Matrix is:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
second matrix is:  [[9 8 7]
 [6 5 4]
 [3 2 1]]
Multiplication of matrix is:  [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## 3. Write a Python Program to transpose a Matrix ?

In [18]:
from numpy import*
M1=matrix("1 2 3 ; 4 5 6 ; 7 8 9")
print(" first Matrix is: ",M1)

M2=M1.transpose()
print("transpose of matrix is: ",M2)

 first Matrix is:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose of matrix is:  [[1 4 7]
 [2 5 8]
 [3 6 9]]


## 4. Write a Python Program to sort Words in an Alphabatical Order ?

In [21]:
my_str = input("Enter a string: ")  
 
words = my_str.split()  

words.sort()  
 
for word in words:  
   print(word)  

Enter a string: boy axe apple bug candy copper zebra umpire lion
apple
axe
boy
bug
candy
copper
lion
umpire
zebra


## 5. Write a Python Program to remove Punctuations From a String ?

In [22]:
def removePunctuatuions():
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    in_string = input('Enter a String: ')
    out_string = ''
    for ele in in_string:
        if ele not in punctuations:
            out_string += ele
    print(out_string)
    
removePunctuatuions()


Enter a String: "Full Stacks DS" @ Ineuron
Full Stacks DS  Ineuron
